# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Treebank
version:      0.10
version_from: Treebank.pm
installdirs:  site
requires:
    Text::Balanced:                1.89

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
